### ISSUE TITLE
icon in activity bar

### ISSUE THREAD

**Issue by Jim-ah** [badsyntax/vscode-gradle#1000]
Extension Name: vscode-gradle
Extension Version:
OS Version:
VSCode version:

I can't see the gradle icon in the activity bar after install, it's not hidden and I can't use it.

**Comment by CsCherrYY** [comment]
Currently the extension will be activated if the current workspace contains `gradlew` or `gradlew.bat`. Could you have a check?

**Comment by brendansailer** [comment]
I'm having the same problem, but it was resolved when adding a gradlew file which is inconvenient. Is there a way to always enable the extension?  My current project uses build.gradle, gradle.properties, and settings.gradle files rather than a gradlew. Thanks for the help!

**Comment by mozhuanzuojing** [comment]
Me too

**Comment by CsCherrYY** [comment]
Currently we need a `gradlew` or `gradlew.bat` to activate the extension, although we have supported local gradle installation since `3.7.0`. We plan to reorganize the condition to activate extension to meet our requirement better, see https://github.com/microsoft/vscode-gradle/issues/1004 for the details.

**Comment by CsCherrYY** [comment]
Closing this issue. If there is any bug or unresolved case, feel free to create a new issue.
